name: Copy Images

on:
  workflow_call:

jobs:
  copy-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create directories
        run: mkdir -p out/

      - name: Copy public images
        run: cp -r public/* out/

      - name: List copied files
        run: ls -la out/ 